services:
  mysql:
    image: mysql:8.0
    container_name: eucomida-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eucomida_database
      MYSQL_USER: eucomida_user
      MYSQL_PASSWORD: eucomida_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_aula:/var/lib/mysql

volumes:
    mysql_data_aula: